fix: [pull] 4.3 from neo4j:4.3 (#4)
* Fix for propagating sorted columns through AggregatingQueryProjection

* Fixing existing test

* Don't add Eager between MATCH(prop) and MERGE(prop) on different labels

* Don't add Eager between MATCH(:A:B) and MERGE(:A:C)

* Fix cherry-picked tests

* MetaDataStore does not refresh fields at runtime

MetaDataStore has a cache of (almost) all fields and had this notion
of checking in all getters if the given field had been initialized,
and if not call "refreshFields" which would read all fields from store
and cache them. This was a silent problem because not all methods
that changed these fields wrote them to the store. I.e. reading
a field at runtime which wasn't initialized would reset all unstored
cached state to that of the stored state.

This is a dangerous behaviour since it could reset fields
seemingly at random, but for a long time it just so happened to not
be a problem because all fields were refreshed at the first "get"
of any field and would not be called after that.

With the introduction of database UUID and external store UUID
this changed a bit because:

- database UUID didn't have a field at all
- external store UUID didn't update the cached field on setting it,
  and could also be "not initialized" when upgrading a store from a
  pre-external-store-UUID era

The particular issue was this, a race between
nextCommittingTransactionId and getExternalStoreId()

- T1 calls nextCommittingTransactionId. lastCommittingTxIdField,
  an AtomicLong field governing this state) is e.g. 6 does
  incrementAndGet and returns 7.
- T2 performs some operation which accesses getExternalStoreId(),
  where the logic was that if the cached state of this field
  was "not initialized" it would call "refreshFields" and replace
  all cached state with that of the store. E.g. the field governing
  lastCommittingTxField would get reset to 6.
- T3 calls nextCommittingTransactionId and will also get back 7.
= There are now multiple transactions committing with transaction ID 7.

The fix is to:

- remove the dangerous notion of refreshing fields at runtime
- let all state have cached fields (database UUID didn't)
- let setting external store UUID also update the cached field
  (like all other setters).
- read all fields when opening the meta data store

* Unflake RestartableImportIT

If the process was killed after the import was completed, but before the process died, a non-zero exit code would make it retry and the next import would complain on existing store-files
Now checks for either exit 0 or the COMPLETED file (written after import)
Also fix the log message on failed imports. Was reporting `Import completed successfully, took 18964d 12h 41m 22s 488ms.` on this failure

* Bump Log4j version

Update Log4j to 2.15.0 to address CVE-2021-44228

* Fixes system graph leak in SHOW commands ()

* Fix flaky truncateNewerTransactionLogFileWhenForced by avoiding random zero bytes, which are treated as start of pre-allocated file tail

* Update link to manual

* updated poms to 4.3.9-SNAPSHOT

* Bump log4j version

Update Log4j to 2.16.0

* Make procedure result type spec covariant

For procedures that return abstract types like `CTNumber`, their type
specs now include `CTNumber` subtypes, i.e. `CTInteger` and `CTFloat`.

* Fix operator state variables scope in Union operator ()

* updated poms to 4.3.10-SNAPSHOT

* Run Namespacer before projecting named paths

* Fix LogicalPlanningTestSupport

* Don't add new slots for argument aliases in union

When the shared argument slots to both the left-hand side and right-hand side
of a Union contains variable name aliases, we do not need to create a new
separate slot for the alias.

This fixes a bug when a Union under an Apply with argument slots containing
aliases is followed by an Optional. When no row is produced (matched), Optional
manufactures a row with only argument values and null-values. In this case the
newly created slot for the variable name alias was only available when an
actual row was produced out of the Union. But with this fix it should now be
able to refer to the aliased argument variable in its original slot, which
should work also for the non-matched rows.

Co-Authored-By: Henrik Nyman <henrik.nyman@neotechnology.com>
Co-Authored-By: Alex Averbuch <alex.averbuch@gmail.com>
Co-Authored-By: Izabela Śmietana <izabela.smietana@neotechnology.com>

* Bump log4j to 2.17

cl: Update Log4j to 2.17 to address CVE-2021-45105

* Fix neo4j/neo4jRemove unnecessary optional matches

* Solves a bug where an optional match that solve the exact same query graph as a preceding match failed in planning.
* Luckily this only happens when the optional match can safely be ignored, so let's just remove it.

* Trim jvm-additional configs

Fixes an issue where trailing spaces on `dbms.jvm.additional` configurations could cause neo4j not to start

* Unflake `Neo4jCommandIT.shouldBeAbleToUpdateRealServerOnWindows`

There seems to be a race with install/update service not waiting for process to finish, thus failing to do the second command as service does not exist yet

* Bump log4j version

Update Log4j to 2.17.1 to address CVE-2021-44832

* updated poms to 4.3.11-SNAPSHOT

* Fix leak of transactional context into query plan cache

The lambdas for online index orderCapability and valueCapability were
accidentally leaking a reference to TransactionBoundPlanContext into
the query plan cache.

(cherry picked from commit fa8ecb2732424f40ccef38045e4125f373502755)

* Update netty to 4.1.73 to address CVE-2021-43797 ()

* Fix locale dependent tests. ()

* Fix bugs in Cypher Shell :param

- Missing add-opens in manifest.
- The expression evaluator sometimes returned values that are not compatible with driver.

* DefaultNodeCursor cannot do a fast degree lookup if the user does not have access to traverse everything, so we should not pretend it can.

* Fix for RecoveryCorruptedTransactionLogIT

* CreateDbTool migrate and upgrade ()

* Extract DbSetup from DbCreator

Extract dbms setup from DbCreator into new DbSetup interface.
This will make it possible to have a DbSetup that unpacks an
existing .zip store and migrate or upgrade instead of creating
a new dbms.

Description used to name homeDirectory, .txt and .zip file is
provided directly by DbDescription instead of as a concatenation
of record format and kernel version.
For custom stores, description can be provided by user using
--description

* ZipUtils can unzip whole sourceZip to targetDirectory

Also inlined
unzip( String sourceZip, Path targetFile ) into
unzipResource( Class<?> klass, String zipName, Path targetFile )

* CreateDbTool has migrate mode

Take existing .zip store and open in current version
with allow_upgrade=true and zip it back down as new
.zip store.

Note! It doesn't do dbms.upgrade().

* CreateDbTool migrate can also upgrade

* Tests for CreateDbTool --migrate

* Address PR comments

- Improve help text
- Correct javadoc for ZipUtils
- Remove left-over print
- Correct test failure description

* Try fix test failure at windows

Can't normalize path that comes from URL.toFile(). Trying to convert to URI instead.

Previous error:
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /Z:/BuildAgent/work/9b7a5724be1663a2/neo4j/private/enterprise/enterprise-it/it-test-support/target/test-classes/com/neo4j/kernel/AF4.1.a_V4.2_empty.zip

* Address PR comments

- Better description for `migrate` mode
- Fix javadoc in ZipUtils

* Remove GC viewer secondary recording ()

* Produce valid plans for previously solved arguments in optional matches

* Update java driver to 4.3.7

* add retries to https communication () ()

* add retries to https communication

* add an alternate suggestion howto do this.

* add actual sleep circle.

* set retries to 50 again.

* added a test and sped up the testing

* make more constructors in order to keep default values private and final

* make style guide happy

* remove debug code

* changed DEFAULT_MAXIMUM_RETRY_BACKOFF to DEFAULT_MAXIMUM_RETRY_BACKOFF_MILLIS

* removed nested try-catch

* reduce amount of try-catch

* review feedback

* revert format

Co-authored-by: Michael Simons <michael.simons@neo4j.com>

Co-authored-by: Michael Simons <michael.simons@neo4j.com>

* Make sure to flush tx log before checkpoint

Seems like we weren't flushing tx logs properly when writing empty tx
for example for batch importer.

* Fix bug in aggregation under limit

We relied on the false assumption that output always has room for all
aggregated rows. Which is not always the case, under limits for
example. Instead, we now put a continuation if output is full.

* neo4j-admin report can take heap dumps again

Fixes a bug in neo4j-admin report command where using the heap classifier would
make the command fail with Error: Failed to write heapdump.hprof

Co-authored-by: Arne Fischereit <arne.fischereit@neo4j.com>
Co-authored-by: Georgiy Kargapolov <inmost-light@users.noreply.github.com>
Co-authored-by: Mattias Finné <mattias@neotechnology.com>
Co-authored-by: Valdemar Roxling <valdemar.roxling@neotechnology.com>
Co-authored-by: emmaholmbergohlsson <emma.holmberg.ohlsson@neo4j.com>
Co-authored-by: Nacho Cordón <ncordon@users.noreply.github.com>
Co-authored-by: Sergey Zaporozhtsev <sergey.zaporozhtsev@neotechnology.com>
Co-authored-by: Pontus Melke <pontusmelke@gmail.com>
Co-authored-by: Gustav Lindroth <gustav.lindroth@neotechnology.com>
Co-authored-by: Sergey Zaporozhtsev <zimmre@gmail.com>
Co-authored-by: Izabela Śmietana <izabela.smietana@neotechnology.com>
Co-authored-by: Gustav Hedengran <gustav.hedengran@neo4j.com>
Co-authored-by: Love Leifland <love.leifland@neotechnology.com>
Co-authored-by: Henrik Nyman <henrik.nyman@neotechnology.com>
Co-authored-by: Alex Averbuch <alex.averbuch@gmail.com>
Co-authored-by: gjmwoods <42248895+gjmwoods@users.noreply.github.com>
Co-authored-by: Michael Simons <michael.simons@neo4j.com>
Co-authored-by: Mark Dixon <1756429+mnd999@users.noreply.github.com>
Co-authored-by: Anton Persson <anton.persson@neotechnology.com>
Co-authored-by: Greg <GregHib@users.noreply.github.com>
Co-authored-by: Bastien Louërat <bastien.louerat@neo4j.com>
Co-authored-by: Johannes Unterstein <johannes.unterstein@neotechnology.com>