fix: [pull] 4.4 from neo4j:4.4 (#11)
* Update the definition of Identifier for the javacc parser

The parser didn't accept the same set of unicode characters as the parboiled parser.

* Add unused parts of the ast generator

* Fix for propagating sorted columns through AggregatingQueryProjection

* Fixing existing test

* Concat with empty list should return same item representation

* MetaDataStore does not refresh fields at runtime

MetaDataStore has a cache of (almost) all fields and had this notion
of checking in all getters if the given field had been initialized,
and if not call "refreshFields" which would read all fields from store
and cache them. This was a silent problem because not all methods
that changed these fields wrote them to the store. I.e. reading
a field at runtime which wasn't initialized would reset all unstored
cached state to that of the stored state.

This is a dangerous behaviour since it could reset fields
seemingly at random, but for a long time it just so happened to not
be a problem because all fields were refreshed at the first "get"
of any field and would not be called after that.

With the introduction of database UUID and external store UUID
this changed a bit because:

- database UUID didn't have a field at all
- external store UUID didn't update the cached field on setting it,
  and could also be "not initialized" when upgrading a store from a
  pre-external-store-UUID era

The particular issue was this, a race between
nextCommittingTransactionId and getExternalStoreId()

- T1 calls nextCommittingTransactionId. lastCommittingTxIdField,
  an AtomicLong field governing this state) is e.g. 6 does
  incrementAndGet and returns 7.
- T2 performs some operation which accesses getExternalStoreId(),
  where the logic was that if the cached state of this field
  was "not initialized" it would call "refreshFields" and replace
  all cached state with that of the store. E.g. the field governing
  lastCommittingTxField would get reset to 6.
- T3 calls nextCommittingTransactionId and will also get back 7.
= There are now multiple transactions committing with transaction ID 7.

The fix is to:

- remove the dangerous notion of refreshing fields at runtime
- let all state have cached fields (database UUID didn't)
- let setting external store UUID also update the cached field
  (like all other setters).
- read all fields when opening the meta data store

* Don't add Eager between MATCH(prop) and MERGE(prop) on different labels

* Don't add Eager between MATCH(:A:B) and MERGE(:A:C)

* allow local aliases for read only configuration

* Unflake RestartableImportIT

If the process was killed after the import was completed, but before the process died, a non-zero exit code would make it retry and the next import would complain on existing store-files
Now checks for either exit 0 or the COMPLETED file (written after import)
Also fix the log message on failed imports. Was reporting `Import completed successfully, took 18964d 12h 41m 22s 488ms.` on this failure

* Case insensitive `WHERE` sub-clauses in old paraboiled parser

* Bump log4j version

Update Log4j to 2.15.0 to address CVE-2021-44228

* Update to driver version 4.4.2

* Using aggregation alias in order is not deprecated

* Fixes system graph leak in SHOW commands ()

* Ensure SSR error message only appears when the error is about writing in read mode ()

* Fix flaky truncateNewerTransactionLogFileWhenForced by avoiding random zero bytes, which are treated as start of pre-allocated file tail

* Fix operator state variables scope in Union operator ()

* updated poms to 4.4.2-SNAPSHOT

* Bump log4j version

Update Log4j to 2.16.0

* Make procedure result type spec covariant

For procedures that return abstract types like `CTNumber`, their type
specs now include `CTNumber` subtypes, i.e. `CTInteger` and `CTFloat`.

* updated poms to 4.4.3-SNAPSHOT

* Unflake transaction tests attempt 2 ()

* Fix bugs in Cypher Shell :connect command

- Set username in all paths of connect
- Throw exceptions before modifying connection state

* add runtime spec test for Union with alias argument

* Bump log4j to 2.17

cl: Update Log4j to 2.17 to address CVE-2021-45105

* Remove unnecessary optional matches

* Solves a bug where an optional match that solve the exact same query graph as a preceding match failed in planning.
* Luckily this only happens when the optional match can safely be ignored, so let's just remove it.

* Run Namespacer before projecting named paths

* Fix LogicalPlanningTestSupport

* Update error message when running unsupported syntax in explicit transaction

* Fix `Expected positive int value, got 0` error

changelog: Fix `Expected positive int value, got 0` error with `CALL ... IN TRANSACTIONS`
when there were an empty map in scope.

* Code review: simplify

* Fix line continuation indentation in Cypher Shell

* Fixes an issue importing large duplicate IDs

Where if an ID from the e.g. CSV input file was large and required
a dynamic record (when stored in the temporary ID property store)
the wrong StoreCursors were passed in so that it would write into
the wrong store. This didn't cause other problems because any
property data for the node would be written afterwards and overwrite
it, but the node ID --> actual ID would throw exception later
if any of those large IDs had duplicates.

* Closed kernel transaction on periodic transaction context commit

Before this PR every transactional context commit (used during periodic commit queries) was causing kernel transaction leak. As result eventually, the system will refuse to start any kernel transaction since the limit active kernel transactions will be reached.

* Trim jvm-additional configs

Fixes an issue where trailing spaces on `dbms.jvm.additional` configurations could cause neo4j not to start

* Unflake `Neo4jCommandIT.shouldBeAbleToUpdateRealServerOnWindows`

There seems to be a race with install/update service not waiting for process to finish, thus failing to do the second command as service does not exist yet

* Fixes an array index issue in EncodingIdMapper

If there are multiple items with the same encoded value
then "get" will have to look through them to find which one
to actually get. This method would use the wrong "highest set index"
when navigating the array.

* Bump log4j version

Update Log4j to 2.17.1 to address CVE-2021-44832

* Includes relationship lookup index in diagnostics/memrec

* updated poms to 4.4.4-SNAPSHOT

* Fix leak of transactional context into query plan cache

The lambdas for online index orderCapability and valueCapability were
accidentally leaking a reference to TransactionBoundPlanContext into
the query plan cache.

* Fix CoerceToPredicate pretty-printing

* Improve UNWIND + CALL IN TRANSACTIONS performance

- Don't copy lists produced by range()
- Cache other lists to avoid copying the same data over and over

* Don't cache maps as it makes LOAD CSV queries slower

* Update netty to 4.1.73.Final to address CVE-2021-43797 ()

Update netty to 4.1.73-Final to address CVE-2021-43797

* Log RaftMemberIds in DiagnosticsManager

* Fix locale dependent tests. ()

* Fix PrettyIRTest ()

* Fix bugs in Cypher Shell :param

- Missing add-opens in manifest.
- The expression evaluator sometimes returned values that are not compatible with driver.

* Fix for RecoveryCorruptedTransactionLogIT

* DefaultNodeCursor cannot do a fast degree lookup if the user does not have access to traverse everything, so we should not pretend it can.

* Adds blocklist of ip addresses for LOAD CSV ()

* Remove GC viewer secondary recording ()

* CreateDbTool migrate and upgrade ()

* Extract DbSetup from DbCreator

Extract dbms setup from DbCreator into new DbSetup interface.
This will make it possible to have a DbSetup that unpacks an
existing .zip store and migrate or upgrade instead of creating
a new dbms.

Description used to name homeDirectory, .txt and .zip file is
provided directly by DbDescription instead of as a concatenation
of record format and kernel version.
For custom stores, description can be provided by user using
--description

* ZipUtils can unzip whole sourceZip to targetDirectory

Also inlined
unzip( String sourceZip, Path targetFile ) into
unzipResource( Class<?> klass, String zipName, Path targetFile )

* CreateDbTool has migrate mode

Take existing .zip store and open in current version
with allow_upgrade=true and zip it back down as new
.zip store.

Note! It doesn't do dbms.upgrade().

* CreateDbTool migrate can also upgrade

* Tests for CreateDbTool --migrate

* Address PR comments

- Improve help text
- Correct javadoc for ZipUtils
- Remove left-over print
- Correct test failure description

* Try fix test failure at windows

Can't normalize path that comes from URL.toFile(). Trying to convert to URI instead.

Previous error:
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /Z:/BuildAgent/work/9b7a5724be1663a2/neo4j/private/enterprise/enterprise-it/it-test-support/target/test-classes/com/neo4j/kernel/AF4.1.a_V4.2_empty.zip

* Address PR comments

- Better description for `migrate` mode
- Fix javadoc in ZipUtils

* Transaction memory tracker allocator test checks

- Make sure that allocator is always empty on transaction init
- Fail on allocation calls on closed transaction allocator
- Verify that released bytes can be actually released

* Close query state once

Authored-by: Pontus Melke

* Avoid double release in ResourceManager::clear

Authored-by: Pontus Melke

* Isolate and fix memory tracking tests

* Update neo4j-java-driver to 4.4.3 ()

* Produce valid plans for previously solved arguments in optional matches

* Follows redirect url to resolve blocked LOAD CSV urls ()

* Introduce 'access-mode' header to HTTP Cypher API ()

Introduce 'access-mode' header to allow for customizable routing in HTTP Cyhpher API

* Disable all logging in Cypher Shell

* Wait for transactions to complete on system before continuing test

The system transactions weren't completed in some cases before the test
checked for the open transactions resulting in flaky behavious.

* fix password parameter as home database bug when creating databases ()

* fix bug by doing password converter last in the mapValueConverter

* make sure password parameter is unique

* move test case to appropriate section in the test file

* Do not automatically consider properties to overlap if they use index access

* Should not fail planning when XORing two identical range predicates

* Ensure ANDed identical predicates are merged before literal extraction

* updated poms

* Cache slimmed version of LogicalPlanState

* Make sure to flush tx log before checkpoint

Seems like we weren't flushing tx logs properly when writing empty tx
for example for batch importer.

* Fix bug in aggregation under limit

We relied on the false assumption that output always has room for all
aggregated rows. Which is not always the case, under limits for
example. Instead, we now put a continuation if output is full.

* Consistency checker tweaks page cache mem setting for optimal perf

 When running the `check-consistency` admin command, and admin commands
 in general the page cache memory setting is read from neo4j.conf.
 That setting is typically set quite high to get good performance
 when running the neo4j dbms. However when doing a consistency check
 the optimal performance is reached when there's a certain amount of
 available off-heap memory for special caches managed by the checker.
 The consistency checker can now spot if that setting is set too high
 for this scenario and reduce it, resulting in better consistency check
 performance.

* Fix flakiness in show transaction tests

Add filtering when possible and wrap in eventually in other cases.
Also add more verbose output for one flaky test we don't know the cause of.

Co-authored-by: Therese Magnusson <therese.magnusson@neotechnology.com>

* Remove old try to unflake tests

Co-authored-by: Therese Magnusson <therese.magnusson@neotechnology.com>

* KernelTransactions registers tx memory pool in init

Instead of in constructor. This fixes a problem where encountering
an error during Database#init would not remove that pool, i.e.
it would not properly clean up after itself. This would poison
the in-memory state of the dbms such that that particular database
could not be started again (at least if e.g. metrics were enabled
since there would now be two pools (the second registered on the
second start of that db) for which to register metrics,
and the metrics registry is global, requiring unique names.

* Removes DatabaseConfig listeners on shutdown

Instead of in stop. This fixes a problem where listeners
added during init stage would not be removed if database start
would fail, causing listeners to remain in the global config.

* Boot loader fix for detecting running instance on Windows

When detecting if Neo4j Windows server is running the output from
Powershell Get-service is used and if any outputted line from that
command includes the name of the service (default neo4j) and does not
include the word "Stopped" we say that the service is running.

BUT at least on Windows Server 2019 the output to stderr includes
something like:

Get-service  : Cannot find any service with service name 'neo4j'
...

So, do not include stderr when detecting...

* neo4j-admin report can take heap dumps again

Fixes a bug in neo4j-admin report command where using the heap classifier would make the command fail with Error: Failed to write heapdump.hprof

* Do not register any query in the disabled recent query buffer.

Previously even a disabled query buffer would allocate some memory in the memory tracker and will report those bytes as used while in reality, they are not.
Also, that incorrectly reported memory will never be released back.

* Address NPE in StatementProcessorTxManager by making interrupts inter… ()

Address NPE in StatementProcessorTxManager by making interupt() and transactionStatus() interaction with statmentProcessor map atomic.

* Attempt to prevent race between bolt and netty threads interaction with the netty pipeline ()

Co-authored-by: Olivia Ytterbrink <olivia.ytterbrink@neotechnology.com>
Co-authored-by: Arne Fischereit <arne.fischereit@neo4j.com>
Co-authored-by: linneaandersson <Linneamaria10@gmail.com>
Co-authored-by: Mattias Finné <mattias@neotechnology.com>
Co-authored-by: Georgiy Kargapolov <inmost-light@users.noreply.github.com>
Co-authored-by: Nadja Müller <nadja.muller@neotechnology.com>
Co-authored-by: Valdemar Roxling <valdemar.roxling@neotechnology.com>
Co-authored-by: Bastien Louërat <bastien.louerat@neo4j.com>
Co-authored-by: emmaholmbergohlsson <emma.holmberg.ohlsson@neo4j.com>
Co-authored-by: Pontus Melke <pontusmelke@gmail.com>
Co-authored-by: Nacho Cordón <ncordon@users.noreply.github.com>
Co-authored-by: gjmwoods <42248895+gjmwoods@users.noreply.github.com>
Co-authored-by: Sergey Zaporozhtsev <sergey.zaporozhtsev@neotechnology.com>
Co-authored-by: Izabela Śmietana <izabela.smietana@neotechnology.com>
Co-authored-by: Gustav Lindroth <gustav.lindroth@neotechnology.com>
Co-authored-by: Sergey Zaporozhtsev <zimmre@gmail.com>
Co-authored-by: Therese Magnusson <therese.magnusson@neotechnology.com>
Co-authored-by: Love Kristofer Leifland <love.leifland@neotechnology.com>
Co-authored-by: alexaverbuch <alex.averbuch@gmail.com>
Co-authored-by: Gustav Hedengran <gustav.hedengran@neo4j.com>
Co-authored-by: MishaDemianenko <12656787+mishademianenko@users.noreply.github.com>
Co-authored-by: Henrik Nyman <henrik.nyman@neotechnology.com>
Co-authored-by: Balazs Lendvai <balazs.lendvai@neotechnology.com>
Co-authored-by: Michael Simons <michael.simons@neo4j.com>
Co-authored-by: Mark Dixon <1756429+mnd999@users.noreply.github.com>
Co-authored-by: Greg <GregHib@users.noreply.github.com>
Co-authored-by: Anton Persson <anton.persson@neotechnology.com>
Co-authored-by: Hannes Sandberg <HannesSandberg@users.noreply.github.com>
Co-authored-by: AlexicaWright <49636617+AlexicaWright@users.noreply.github.com>
Co-authored-by: Peter Wilhelmsson <peter.wilhelmsson@neo4j.com>